harbour-storeman-installer → "$called"

diff --git a/bin/harbour-storeman-installer b/bin/harbour-storeman-installer
--- a/bin/harbour-storeman-installer
+++ b/bin/harbour-storeman-installer
@@ -31,14 +31,14 @@ called="$(basename "$0")"
 # Create logfile:
 logfile="/var/log/$called_$(date +'%Ft%H-%M-%S').log.txt"
 if ! touch "$logfile"
-then printf '%s\n' "[Error] Failed to touch logfile ${logfile}" | systemd-cat -t harbour-storeman-installer -p 4 || true
+then printf '%s\n' "[Error] Failed to touch logfile ${logfile}" | systemd-cat -t "$called" -p 4 || true
 fi
 
 # Write first entry to logfile:
 logentry="[Info] Touch'ed logfile: ${logfile}"
 if printf '%s\n' "$(date -Ins)  $logentry" >> "$logfile"
-then printf '%s\n' "$logentry" | systemd-cat -t harbour-storeman-installer -p 6 || true
-else printf '%s\n' "[Error] Failed to write to ${logfile}" | systemd-cat -t harbour-storeman-installer -p 4 || true
+then printf '%s\n' "$logentry" | systemd-cat -t "$called" -p 6 || true
+else printf '%s\n' "[Error] Failed to write to ${logfile}" | systemd-cat -t "$called" -p 4 || true
 fi
 
 # Check for root privileges:
@@ -46,19 +46,19 @@ if ! printf '%s' " $(id -un) $(id -Gn) " | grep -Fq ' root '
 then
   logentry="[Warning] $called should be started with root privileges, because it does not provide a polkit rule for users any longer."
   printf '%s\n' "$(date -Ins)  $logentry" >> "$logfile" || true
-  printf '%s\n' "$logentry" | systemd-cat -t harbour-storeman-installer -p 5 || true
+  printf '%s\n' "$logentry" | systemd-cat -t "$called" -p 5 || true
 fi
 
 # Serves as a synchronisation point, because pkcon sub-commands wait
 # until the package management system is idle:
 logentry="pkcon repo-set-data harbour-storeman-obs refresh-now true"
 printf '\n%s\n' "$(date -Ins)  $logentry" >> "$logfile" || true
-printf '%s\n' "[Debug] Execute: $logentry" | systemd-cat -t harbour-storeman-installer -p 7 || true
+printf '%s\n' "[Debug] Execute: $logentry" | systemd-cat -t "$called" -p 7 || true
 if pkcon repo-set-data harbour-storeman-obs refresh-now true >> "$logfile" 2>&1
 then
   logentry="pkcon -y install harbour-storeman"
   printf '\n%s\n' "$(date -Ins)  $logentry" >> "$logfile" || true
-  printf '%s\n' "[Debug] Execute: $logentry" | systemd-cat -t harbour-storeman-installer -p 7 || true
+  printf '%s\n' "[Debug] Execute: $logentry" | systemd-cat -t "$called" -p 7 || true
   # The following statement must be started detached ("&"), because this
   # script file will be removed in the process, which will likely fail,
   # if it is still opened for executing / reading.
@@ -66,5 +66,5 @@ then
 else
   logentry="[Critical] Aborting to install harbour-storeman, because error-code $? was returned by: $logentry"
   printf '%s\n' "$(date -Ins)  $logentry" >> "$logfile" || true
-  printf '%s\n' "$logentry" | systemd-cat -t harbour-storeman-installer -p 3 || true
+  printf '%s\n' "$logentry" | systemd-cat -t "$called" -p 3 || true
 fi
