Split one log output in two, spatially & temporally (#161)

diff --git a/bin/harbour-storeman-installer b/bin/harbour-storeman-installer
--- a/bin/harbour-storeman-installer
+++ b/bin/harbour-storeman-installer
@@ -40,6 +40,13 @@ if [ -s "$logfile" ]
 then linebreaks="\n\n\n"
 fi
 
+# Write first entry to logfile:
+logentry="[Info] Logging to $logfile"
+if printf "${linebreaks}%s\n" "$(date -Iseconds) $logentry" >> "$logfile"
+then printf '%s\n' "$logentry" | systemd-cat -t "$called" -p 6 || true
+systemd-cat -t "$called" -p 4 printf '%s\n' "[Error] $pkgname failed to write to $logfile" || true
+fi
+
 # Even when started interactively, another pkcon job may have just been
 # started, hence provide pkcon with a little time to enqueue it, because
 # otherwise pkcon might fail enqueuing the next pkcon-job.
@@ -49,12 +56,10 @@ sleep 1
 # backend (on SailfishOS: libzypp) is idle:
 pkgname="$(pkcon -p search name "$called" | grep '^Installed ' | tr -s ' ' | cut -f 2 -d ' ' | rev | cut -f 2- -d '.' | rev | grep -m 1 "^$called-[0-9]")"
 
-# Write first entry to logfile:
-logentry="[Info] $pkgname touch'ed $logfile"
-if printf "${linebreaks}%s\n" "$(date -Iseconds) $logentry" >> "$logfile"
-then printf '%s\n' "$logentry" | systemd-cat -t "$called" -p 6 || true
-systemd-cat -t "$called" -p 4 else printf '%s\n' "[Error] $pkgname failed to write to $logfile" || true
-fi
+# Write $pkgname to logfile:
+logentry="[Debug] Installed, now running: $pkgname"
+printf '\n%s\n' "$(date -Iseconds) $logentry" >> "$logfile" || true
+systemd-cat -t "$called" -p 7 printf '%s\n' "$logentry" || true
 
 # Out of occasional bad experience when pkcon is being hammered with
 # commands, also prefix `pkcon repo-set-data` with a second sleep:
