Rework failing repo refersh section and behaviour

diff --git a/bin/harbour-storeman-installer b/bin/harbour-storeman-installer
--- a/bin/harbour-storeman-installer
+++ b/bin/harbour-storeman-installer
@@ -5,6 +5,9 @@ set -u  # Do not use "-f" (disable pathname expansion) and "-C" (no-clobber /
 #set -o pipefail  # Not used (yet), hence also dropping interpreter #!/bin/bash
 #export POSIXLY_CORRECT=1  # Leave it for now, can have side-effects (positive and negative), apparently not needed (yet).
 export LC_ALL=POSIX  # For details see https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html#tag_08_02
+export mypid="$$"
+umask 7113  # The first octal digit is ignored by most implementations
+cd /tmp  # Set PWD
 
 # Specify bash as interpreter of this script (in its first line), as this ensures
 # that "-o pipefail" is available (for its use in the third line), after checking
@@ -24,9 +27,11 @@ export LC_ALL=POSIX  # For details see https://pubs.opengroup.org/onlinepubs/969
 # Nevertheless, this script is still a Bourne (not-"Again") Shell script and
 # shall stay free of bashisms.
 
-# This script is designed to be called either manually or fully detached
-# (by a "double fork") as the last statement of the %posttrans section 
+# This script is designed to be called fully detached (by a "double fork" /
+# a "daemonize") as the last statement of the %posttrans section 
 # (the last executed) of an RPM spec file.
+# Kill parent, which was made session leader by `setsid --fork`:
+kill "$PPID"
 
 # Memorise how we were called:
 called="$(basename "$0")"
@@ -36,13 +41,25 @@ export logfile="/var/log/${called}.log.txt"
 # Prefix first output with three linebreaks, if logfile size > 0
 linebreaks=""
 if [ -s "$logfile" ]
-then line_breaks="\n\n\n"
+then linebreaks="\n\n\n"
 fi
 
 # Provide RPM with a little time to proceed finishing the RPM transaction,
 # which called this script asynchronously, because pkcon might fail
 # enqueuing a pkcon-job while an RPM transaction is unfinished.
-sleep 2
+i=0
+maxi=60
+rpmXact=running
+while [ $i -lt $maxi ] && ps -eo pid | grep -Fq "$gppid"
+do
+  sleep 1
+  count=$(expr $i + 1)
+done
+if [ $count -ge $maxi ]
+then rpmXact=timedout
+else rpmXact=finished
+fi
+sleep 1
 # `pkcon search name` is also intended to serve as a synchronisation point,
 # because most of pkcon's sub-commands wait until the package management
 # backend (on SailfishOS: libzypp) is idle:
@@ -52,7 +69,7 @@ pkgname="$(pkcon -p search name "$called" | grep '^Installed ' | tr -s ' ' | cut
 logentry="[Info] $pkgname touch'ed $logfile"
 if printf "${linebreaks}%s\n" "$(date -Iseconds) $logentry" >> "$logfile"
 then printf '%s\n' "$logentry" | systemd-cat -t "$called" -p 6 || true
-else printf '%s\n' "[Error] $pkgname failed to write to $logfile" | systemd-cat -t "$called" -p 4 || true
+else systemd-cat -t "$called" -p 4 printf '%s\n' "[Error] $pkgname failed to write to $logfile" || true
 fi
 
 # Out of occasional bad experience when pkcon is being hammered with commands,
@@ -60,38 +77,98 @@ fi
 sleep 1
 logentry="pkcon -pv repo-set-data harbour-storeman-obs refresh-now true"
 printf '\n%s\n' "$(date -Iseconds) [Step 1 / 2] $logentry" >> "$logfile" || true
-printf '%s\n' "[Debug] Execute: $logentry" | systemd-cat -t "$called" -p 7 || true
-if eval $logentry >> "$logfile" 2>&1
-then
-  # Sleeping again for a second between the two pkcon calls, because pkcon
-  # *rarely* fails installing a package ("not found") immediately after an
-  # individual repository refresh via `repo-set-data <repo> refresh-now true`:
-  sleep 1
-  export logentry="pkcon -pvy install harbour-storeman"
-  printf '\n%s\n' "$(date -Iseconds) [Step 2 / 2] $logentry" >> "$logfile" || true
-  printf '%s\n' "[Debug] Execute: $logentry" | systemd-cat -t "$called" -p 7 || true
-  # The following statement must be started fully detached ("double fork" /
-  # "daemonize": first a detached sub shell, in which pwd, umask might and
-  # session-id must be set anew (i.e., the execution environment), then again
-  # the command proper to run as new session-leader), because this script file
-  # will be removed in the process, which will likely fail, if it is still
-  # opened for executing / reading.
-  # It also shall always be the last command issued (WRT control-flow).
-  (eval setsid --fork $logentry >> "$logfile" 2>&1 < /dev/null) >> "$logfile" 2>&1 < /dev/null &
-  # "Daemonizing" / double-forking in shell-style, though I did not manage for
-  # the grandchild *not* to be a session leader (i.e., to fork again with a
-  # single shell expression).  PWD and umask do not need to be set anew, here.
-  retc=0
-else
+systemd-cat -t "$called" -p 7 printf '%s\n' "[Debug] Execute: $logentry" || true
+maxi=5
+maxihalf=$(expr $maxi / 2)
+for i in $(seq -s ' ' $maxi)
+do
+  eval $logentry >> "$logfile" 2>&1
   retc=$?
-  logentry="[Critical] Aborting to install harbour-storeman, because error-code $retc was returned by: $logentry"
-  printf '\n%s\n' "$(date -Iseconds) $logentry" >> "$logfile" || true
-  printf '%s\n' "$logentry" | systemd-cat -t "$called" -p 3 || true
-  sleep 1
-  export logentry="pkcon -pvy remove $called"
-  printf '\n%s\n' "$(date -Iseconds) [Self-removal] $logentry" >> "$logfile" || true
-  printf '%s\n' "[Info] Execute: $logentry" | systemd-cat -t "$called" -p 6 || true
-  (eval setsid --fork $logentry >> "$logfile" 2>&1 < /dev/null) >> "$logfile" 2>&1 < /dev/null &
-fi
+  wait=$(expr $i \* 2 + 1)
+  if [ $retc = 0 ]
+  then break
+  elif [ $i = 1 ]
+  then
+    logentry="[Warning] Failed to refresh harbour-storeman-obs repository, because error-code $retc was returned by: $logentry"
+    printf '\n%s\n' "$(date -Iseconds) $logentry" >> "$logfile" || true
+    printf '%s\n' "$logentry" | systemd-cat -t "$called" -p 5 || true
+    logentry="[Debug] Sleeping for $wait seconds."
+    printf '\n%s\n' "$(date -Iseconds) $logentry" >> "$logfile" || true
+    systemd-cat -t "$called" -p 7 printf '%s\n' "$logentry" || true
+    sleep $wait
+    logentry="[Info] Retry #$i"
+    printf '\n%s\n' "$(date -Iseconds) $logentry" >> "$logfile" || true
+    systemd-cat -t "$called" -p 6 printf '%s\n' "$logentry" || true
+  elif [ $i -le $maxihalf ]
+  then
+    logentry="[Warning] Failed to refresh harbour-storeman-obs repository, because error-code $retc was returned by: $logentry"
+    printf '\n%s\n' "$(date -Iseconds) $logentry" >> "$logfile" || true
+    printf '%s\n' "$logentry" | systemd-cat -t "$called" -p 5 || true
+    logentry="[Info] Trying to terminate (i.e., sending a "TERM" signal to) all processes named ("ID") `pkcon`, then sleeping for $wait seconds."
+    printf '\n%s\n' "$(date -Iseconds) $logentry" >> "$logfile" || true
+    systemd-cat -t "$called" -p 6 printf '%s\n' "$logentry" || true
+    killall -15 pkcon
+    sleep $wait
+    logentry="[Info] Retry #$i"
+    printf '\n%s\n' "$(date -Iseconds) $logentry" >> "$logfile" || true
+    systemd-cat -t "$called" -p 6 printf '%s\n' "$logentry" || true
+  elif [ $i -lt $maxi ]
+  then
+    logentry="[Error] Failed to refresh harbour-storeman-obs repository, because error-code $retc was returned by: $logentry"
+    printf '\n%s\n' "$(date -Iseconds) $logentry" >> "$logfile" || true
+    printf '%s\n' "$logentry" | systemd-cat -t "$called" -p 4 || true
+    logentry="[Warning] Trying to hang up  (i.e., sending a "HUP" signal to) all processes named ("ID") `pkcon`, then sleeping for $wait seconds."
+    printf '\n%s\n' "$(date -Iseconds) $logentry" >> "$logfile" || true
+    systemd-cat -t "$called" -p 7 printf '%s\n' "$logentry" || true
+    killall -1 pkcon
+    sleep $wait
+    logentry="[Info] Retry #$i"
+    printf '\n%s\n' "$(date -Iseconds) $logentry" >> "$logfile" || true
+    systemd-cat -t "$called" -p 6 printf '%s\n' "$logentry" || true
+  else
+    logentry="[Error] Failed to refresh harbour-storeman-obs repository, because error-code $retc was returned by: $logentry"
+    printf '\n%s\n' "$(date -Iseconds) $logentry" >> "$logfile" || true
+    printf '%s\n' "$logentry" | systemd-cat -t "$called" -p 4 || true
+    logentry="[Warning] Trying to quit  (i.e., sending a "QUIT" signal to) all processes named ("ID") `pkcon`, then sleeping for $wait seconds."
+    printf '\n%s\n' "$(date -Iseconds) $logentry" >> "$logfile" || true
+    systemd-cat -t "$called" -p 7 printf '%s\n' "$logentry" || true
+    killall -3 pkcon
+    sleep $wait
+    logentry="[Info] Retry #$i"
+    printf '\n%s\n' "$(date -Iseconds) $logentry" >> "$logfile" || true
+    systemd-cat -t "$called" -p 6 printf '%s\n' "$logentry" || true
+    logentry="pkcon -pv repo-set-data harbour-storeman-obs refresh-now true"
+    printf '\n%s\n' "$(date -Iseconds) [Step 1 / 2] $logentry" >> "$logfile" || true
+    systemd-cat -t "$called" -p 7 printf '%s\n' "[Debug] Execute: $logentry" || true
+    eval $logentry >> "$logfile" 2>&1 && break  # Was final try successful?
+    logentry="[Critical] Failed to refresh harbour-storeman-obs repository, because error-code $retc was returned by: $logentry"
+    printf '\n%s\n' "$(date -Iseconds) $logentry" >> "$logfile" || true
+    printf '%s\n' "$logentry" | systemd-cat -t "$called" -p 3 || true
+    logentry="[Warning] Scheduling harbour-storeman-installer for removal in 30 seconds, trying to install harbour-storeman despite the failed repository refresh meanwhile."
+    printf '\n%s\n' "$(date -Iseconds) $logentry" >> "$logfile" || true
+    systemd-cat -t "$called" -p 5 printf '%s\n' "$logentry" || true
+    export logentry="pkcon -pvy remove $called"
+    printf '\n%s\n' "$(date -Iseconds) [Self-removal] $logentry" >> "$logfile" || true
+    systemd-cat -t "$called" -p 6 printf '%s\n' "[Info] Scheduled for execution in 30 seconds: $logentry" || true
+    setsid --fork /bin/sh -c '(kill "$PPID"; i=0; while [ $i -lt 9 ] && ps -eo pid | grep -Fq "$mypid"; do sleep 1; i=$(expr $i + 1); done; sleep 30; eval $logentry >> "$logfile" 2>&1 < /dev/null) &' >> "$logfile" 2>&1 < /dev/null
+  fi
+done
+export logentry="pkcon -pvy install harbour-storeman"
+printf '\n%s\n' "$(date -Iseconds) [Step 2 / 2] $logentry" >> "$logfile" || true
+systemd-cat -t "$called" -p 7 printf '%s\n' "[Debug] Execute: $logentry" || true
+# Sleeping again for a second right before the next pkcon call, because pkcon
+# *rarely* fails installing a package ("not found") immediately after an
+# individual repository refresh via `repo-set-data <repo> refresh-now true`.
+# The following statement must be started fully detached ("double fork" /
+# "daemonize": first a detached sub shell, in which pwd, umask might and
+# session-id must be set anew (i.e., the execution environment), then again
+# the command proper to run as new session-leader), because this script file
+# will be removed in the process, which will likely fail, if it is still
+# opened for executing / reading.
+# It also shall always be the last command issued (WRT control-flow).
+setsid --fork /bin/sh -c '(kill "$PPID"; sleep 1; i=0; while [ $i -lt 9 ] && ps -eo pid | grep -Fq "$mypid"; do sleep 1; i=$(expr $i + 1); done; eval $logentry >> "$logfile" 2>&1 < /dev/null) &' >> "$logfile" 2>&1 < /dev/null
+# "Daemonizing" / double-forking ("SysV-style") in Shell code, (ab)using
+# this interpreter instance as first fork.
+# PWD and umask do not need to be set anew here, see line 9.
 exit $retc
 
